theme: minima
title: Geoffrey Logovi's blog
author: 
  name: Geoffrey Logovi
  githubuser: geoffreylgv
description: Developer Relations Engineer, Open Source Community Advocate. 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: classic
